<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <CopyDebugSymbolFilesFromPackages>true</CopyDebugSymbolFilesFromPackages>
    
    <!-- Package metadata -->
    <PackageId>Seq.App.Pushover</PackageId>
    <Version>1.0.0</Version>
    <Authors>Matheus André Riboli</Authors>
    <Description>The Pushover app for Seq (https://getseq.net) formats events as text and sends them via push.</Description>
    <PackageProjectUrl>https://github.com/matheusriboli/Seq.App.Pushover</PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageIconUrl>https://pushover.net/favicon.ico</PackageIconUrl>
    <PackageTags>seq-app seq serilog events pushover</PackageTags>
    <RepositoryUrl>https://github.com/matheusriboli/Seq.App.Pushover</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Seq.Apps" Version="2023.4.0" />
  </ItemGroup>

</Project>